# Config File for f110_wall_follow package

# Wall Follow PID controller gains
kp : 0.6
ki : 0.00015
kd : 0.01

# Wall Follow Parameters

# Hokuyo 10LX has 270 degrees scan
angle_range : 270

# Desired Wall Follow distance in meters
desired_distance_right : 0.9
desired_distance_left : 0.65

# Look-ahead Distance
lookahead_distance : 0.5

# Car Length
car_length : 0.50

# Desired Car Velocity based on Error
error_based_velocities : {low: 5.0, medium: 4.0, high: 2.0}